version: '3'
services:
    app:
        build:
            context: ./
        volumes:
            - .:/var/www
        ports:
            - "8181:8181"
        environment:
            - APP_ENV=local
